#!/usr/bin/env bash

NOTES_DIR=$HOME/.notes
if [ "$1" == "q" ]; then
    $EDITOR $(find $NOTES_DIR/* | fzf)
else
    title=$1
    date=$(date +"%Y-%m-%d")
    if [ $1 ] 
        then title="-$title"
    fi
    $EDITOR "$NOTES_DIR/$date$title.md"
fi
